services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=ecommerce'
    ports:
      - '5432:5432'
