spring:
  liquibase:
    contexts: local
  docker:
    compose:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

async:
  core-pool-size: 2
  max-pool-size: 5
  queue-capacity: 50

websocket:
  allowed-origins: "*"

logging:
  level:
    com:
      gitthub:
        youssefagagg.ecommerceorderprocessor: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        security: DEBUG
