spring:
  liquibase:
    contexts: prod
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 50
        order_updates: true
        order_inserts: true

# Task executor configuration for production
async:
  core-pool-size: 10
  max-pool-size: 50
  queue-capacity: 500

# WebSocket configuration for production
websocket:
  allowed-origins: ${ALLOWED_ORIGINS}

# Logging configuration for production
logging:
  level:
    root: INFO
    com:
      gitthub:
        youssefagagg.ecommerceorderprocessor: INFO
    org:
      springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId:-},,%X{spanId:-}] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId:-},,%X{spanId:-}] %msg%n"

rate-limit:
  capacity: ${RATE_LIMIT_CAPACITY:20}
  refill-tokens: ${RATE_LIMIT_REFILL_TOKENS:20}
  refill-duration: ${RATE_LIMIT_REFILL_DURATION:60}


# Server configuration
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  tomcat:
    max-connections: 10000
    accept-count: 100
    threads:
      min-spare: 20
      max: 200