spring:
  application:
    name: ecommerce-order-processor
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  threads:
    virtual:
      enabled: true
  liquibase:
    contexts: ${spring.profiles.active}
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/master.yaml
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 30
        order_updates: false
        order_inserts: false
    generate-ddl: false
# JWT configuration for local
jwt:
  secret: ${JWT_SECRET:LocalRouhMatrouhSecretKeyLocalRouhMatrouhSecretKey}
  expiration: 86400 # 1 day in seconds
  issuer: ecommerce-order-processor
springdoc:
  swagger-ui.path: /swagger-ui/index.html
  show-actuator: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health
  endpoint:
    health:
      access: unrestricted
      show-details: never
      show-components: when_authorized
    info:
      access: unrestricted
  metrics:
    enable:
      all: true


# Rate limiting configuration
rate-limit:
  # Default rate limit settings (20 requests per minute)
  capacity: 20
  refill-tokens: 20
  refill-duration: 60

  # Endpoint-specific rate limits
  endpoints:
    # Authentication endpoints - stricter limits (5 requests per minute)
    "/api/v1/auth/login":
      capacity: 5
      refill-tokens: 5
      refill-duration: 60
    "/api/v1/auth/register":
      capacity: 3
      refill-tokens: 3
      refill-duration: 60

    # Admin endpoints - moderate limits (10 requests per minute)
    "/api/v1/admin/*":
      capacity: 10
      refill-tokens: 10
      refill-duration: 60

    # Public endpoints - more lenient limits (30 requests per minute)
    "/api/v1/products/*":
      capacity: 30
      refill-tokens: 30
      refill-duration: 60
