spring:
  application:
    name: ecommerce-order-processor
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  threads:
    virtual:
      enabled: true
  liquibase:
    contexts: ${spring.profiles.active}
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/master.yaml
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        default_batch_fetch_size: 30
        statement_inspector: null
        order_updates: false
        order_inserts: false
    generate-ddl: false

# JWT configuration for local
jwt:
  secret: LocalRouhMatrouhSecretKeyLocalRouhMatrouhSecretKey
  expiration: 86400 # 1 day in seconds
  issuer: ecommerce-order-processor
