spring:
  application:
    name: ecommerce-order-processor
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  threads:
    virtual:
      enabled: true
  liquibase:
    contexts: ${spring.profiles.active}
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/master.yaml
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 30
        order_updates: false
        order_inserts: false
    generate-ddl: false
# JWT configuration for local
jwt:
  secret: LocalRouhMatrouhSecretKeyLocalRouhMatrouhSecretKey
  expiration: 86400 # 1 day in seconds
  issuer: ecommerce-order-processor
springdoc:
  # Configure Swagger UI for minimal resource usage
  swagger-ui.path: /swagger-ui/index.html
  show-actuator: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId:-},,%X{spanId:-}] %msg%n"
  level:
    com:
      gitthub:
        youssefagagg.ecommerceorderprocessor: DEBUG
