services:
  app:
    container_name: ecommerce-order-processor
    image: 'ghcr.io/youssefagagg/backend-java-task-2025:latest'
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ecommerce'
      - 'SPRING_DATASOURCE_USERNAME=ecommerce'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    depends_on:
      - postgres

  postgres:
    container_name: postgres-ecommerce
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=ecommerce'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
