services:
  app:
    container_name: ecommerce-order-processor
    image: 'ghcr.io/youssefagagg/backend-java-task-2025:latest'
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      - 'SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}'
      - 'SPRING_DATASOURCE_URL=${DB_URL}'
      - 'SPRING_DATASOURCE_USERNAME=${DB_USERNAME}'
      - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}'
      - 'ALLOWED_ORIGINS=${ALLOWED_ORIGINS}'
      - 'RATE_LIMIT_CAPACITY=${RATE_LIMIT_CAPACITY}'
      - 'RATE_LIMIT_REFILL_TOKENS=${RATE_LIMIT_REFILL_TOKENS}'
      - 'RATE_LIMIT_REFILL_DURATION=${RATE_LIMIT_REFILL_DURATION}'
      - 'SERVER_PORT=${SERVER_PORT}'
    depends_on:
      - postgres

  postgres:
    container_name: postgres-ecommerce
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
