package com.gitthub.youssefagagg.ecommerceorderprocessor.dto;

import com.gitthub.youssefagagg.ecommerceorderprocessor.entity.Payment;
import com.gitthub.youssefagagg.ecommerceorderprocessor.entity.PaymentStatus;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * DTO for {@link Payment}.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
public class PaymentDTO {

  private Long id;

  @NotNull
  private Long orderId;

  @NotNull
  @DecimalMin(value = "0.0",
              inclusive = false)
  private BigDecimal amount;

  @NotNull
  private PaymentStatus status;

  @NotNull
  @Size(min = 2,
        max = 50)
  private String paymentMethod;

  @Size(max = 100)
  private String transactionId;

  /**
   * Idempotency key to prevent duplicate payment processing. This should be a unique value
   * generated by the client for each payment attempt.
   */
  @Size(max = 100)
  private String idempotencyKey;
}
